# Generated by Django 4.2.6 on 2023-10-12 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('charge', models.CharField(max_length=200)),
                ('profit', models.CharField(max_length=200)),
                ('gst', models.CharField(max_length=200)),
                ('tds', models.CharField(max_length=200)),
                ('api_txn_id', models.CharField(max_length=200)),
                ('txn_id', models.CharField(max_length=200)),
                ('pay_id', models.CharField(max_length=200)),
                ('ref_id', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('remark', models.CharField(max_length=200)),
                ('optional_1', models.CharField(max_length=200)),
                ('optional_2', models.CharField(max_length=200)),
                ('optional_3', models.CharField(max_length=200)),
                ('optional_4', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('r_type', models.CharField(max_length=200)),
                ('via', models.CharField(max_length=200)),
                ('balance', models.CharField(max_length=200)),
                ('transection_type', models.CharField(max_length=200)),
                ('product', models.CharField(max_length=200)),
                ('w_profit', models.CharField(max_length=200)),
                ('s_profit', models.CharField(max_length=200)),
                ('d_profit', models.CharField(max_length=200)),
                ('r_profit', models.CharField(max_length=200)),
                ('api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.apimanager')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.provider')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'default_permissions': ['add', 'change', 'delete', 'view'],
            },
        ),
    ]
