# Generated by Django 4.2.6 on 2023-10-12 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_reports_credit_by_alter_reports_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='transection_pin',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='credit_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
