# Generated by Django 4.2.6 on 2023-10-12 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userprofile_transection_pin_alter_reports_credit_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sms_url',
            field=models.CharField(default=4, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
