# Generated by Django 4.2.6 on 2023-10-13 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_company_sms_url_company_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='wallet_ammount',
        ),
        migrations.AddField(
            model_name='account',
            name='wallet_ammount',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='LoadWalletRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('bankname', models.CharField(max_length=500)),
                ('amount', models.CharField(max_length=50)),
                ('payment_mode', models.CharField(max_length=500)),
                ('pay_date', models.CharField(max_length=500)),
                ('ref_number', models.CharField(max_length=200)),
                ('remark', models.CharField(max_length=500)),
                ('slip', models.ImageField(upload_to='slip/')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accepted_by', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'default_permissions': ['add', 'change', 'delete', 'view'],
            },
        ),
    ]
