# Generated by Django 4.2.6 on 2023-10-15 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_userprofile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='aeps_onboarding',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
