# Generated by Django 4.2.6 on 2023-10-16 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_userprofile_aeps_onboarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='EkoBankList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('BANK_NAME', models.CharField(max_length=50)),
                ('SHORT_CODE', models.CharField(max_length=50)),
                ('IMPS_STATUS', models.CharField(max_length=50)),
                ('NEFT_STATUS', models.CharField(max_length=50)),
                ('ISVERIFICATIONAVAILABLE', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
                'default_permissions': ['add', 'change', 'delete', 'view'],
            },
        ),
    ]
