# Generated by Django 4.2.6 on 2023-10-16 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_ekobanklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_aadhar',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_account',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_pan',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
