# Generated by Django 4.2.6 on 2023-10-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_alter_userprofile_distributer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_gst',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
